---
- name: Create a directory for thelounge if it does not exist
  become: true
  ansible.builtin.file:
    path: "{{ docker_home_dir }}/thelounge"
    state: directory
    mode: '0755'
    owner: "{{ docker_user }}"
    group: "{{ docker_user }}"

- name: Copy templated files into place.
  ansible.builtin.template:
    src: templates/{{ item.src }}
    dest: "{{ docker_home_dir }}/thelounge/{{ item.dest }}"
    mode: 0644
    owner: "{{ docker_user }}"
    group: "{{ docker_user }}"
  loop:
    - src: docker-compose.yml.j2
      dest: docker-compose.yml
      become: false
  notify: "Restart thelounge"
