---
- name: Initial start gitea
  community.docker.docker_compose:
    project_src: "{{ docker_home_dir }}/gitea/"
    build: false
    restarted: true
  notify: Restart gitea

- name: Restart gitea
  ansible.builtin.shell: "sleep 10 && {{ docker_home_dir }}/gitea/restart.sh"
