---
- name: Copy configs from temp dir.
  become: true
  ansible.builtin.copy:
    src: /home/{{ item }}/dotfiles-tmp/
    dest: /home/{{ item }}/
    remote_src: yes
    directory_mode: yes
    group: "{{ item }}"
    owner: "{{ item }}"
  with_items: "{{ os_users }}"

- name: Remove temp dir.
  become: true
  ansible.builtin.command: rm -rf /home/{{ item }}/dotfiles-tmp
  with_items: "{{ os_users }}"

- name: Remove .git from home.
  become: true
  ansible.builtin.command: rm -rf /home/{{ item }}/.git
  with_items: "{{ os_users }}"

- name: Apply changes to git config.
  become: true
  ansible.builtin.command: /usr/bin/git --git-dir=/home/{{ item }}/.dotfiles/ --work-tree=/home/{{ item }} config status.showUntrackedFiles no
  with_items: "{{ os_users }}"
