---
- name: Copy configs from temp dir.
  ansible.builtin.copy:
    src: /home/{{ ansible_user }}/dotfiles-tmp/
    dest: /home/{{ ansible_user }}/
    remote_src: yes
    directory_mode: yes
    group: "{{ ansible_user }}"
    owner: "{{ ansible_user }}"

- name: Remove temp dir.
  ansible.builtin.command: rm -rf /home/{{ ansible_user }}/dotfiles-tmp

- name: Remove .git from home.
  ansible.builtin.command: rm -rf /home/{{ ansible_user }}/.git

- name: Apply changes to git config.
  ansible.builtin.command: /usr/bin/git --git-dir=/home/{{ ansible_user }}/.dotfiles/ --work-tree=/home/{{ ansible_user }} config status.showUntrackedFiles no
