- name: install packages
  package:
    name: "{{ item }}"
    state: present
  loop:
    - "{{ init_packages }}"

- name: Add os users
  user:
    name: "{{ item }}"
    state: present
    groups: wheel
    append: yes
    createhome: yes
  with_items: "{{ os_users }}"

- name: Add SSH public keys
  authorized_key:
    user: "{{ item }}"
    state: present
    key: "{{ lookup('file', 'keys/{{ item }}') }}"
  with_items: "{{ os_users }}"
