---
- name: update apt cache
  become: true
  ansible.builtin.apt:
    update_cache: yes
  when: ansible_pkg_mgr == "apt"

- name: update yum cache
  become: true
  ansible.builtin.yum:
    update_cache: yes
  when: ansible_pkg_mgr == "yum"

- name: update apk cache
  become: true
  community.general.apk:
    update_cache: yes
  when: ansible_pkg_mgr == "apk"

- name: update dnf cache
  become: true
  ansible.builtin.dnf:
    update_cache: yes
  when: ansible_pkg_mgr == "dnf"

- name: update zypper cache
  become: true
  community.general.zypper:
    name: zypper
    update_cache: yes
  when: ansible_pkg_mgr == "zypper"

- name: update pacman cache
  become: true
  community.general.pacman:
    update_cache: yes
  when: ansible_pkg_mgr == "pacman"

- name: install base packages
  become: true
  package:
    name: "{{ item }}"
    state: present
  loop:
    - "{{ init_packages }}"

- name: Make sure a wheel group is present
  become: true
  group:
    name: wheel
    state: present

- name: sudo for wheel group
  become: true
  copy:
    content: '%wheel ALL=(ALL:ALL) NOPASSWD: ALL'
    dest: /etc/sudoers.d/wheel_nopasswd
    mode: 0440

- name: Add os user
  become: true
  user:
    name: "{{ ansible_user }}"
    state: present
    groups: wheel
    append: yes
    createhome: yes
    shell: /bin/bash


- name: Add SSH public keys
  authorized_key:
    user: "{{ ansible_user }}"
    state: present
    key: "{{ lookup('file', 'keys/{{ ansible_user }}') }}"

- name: Disallow SSH password authentication
  become: true
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "{{ item.From }}"
    line: "{{ item.To }}"
    state: present
  with_items:
    - { From: 'PasswordAuthentication yes', To: 'PasswordAuthentication no' }
    - { From: '#PubkeyAuthentication yes', To: 'PubkeyAuthentication yes' }
  notify:
    - restart sshd
