---
- name: Check whether the dotfiles directory already exists.
  ansible.builtin.stat:
    path: /home/{{ ansible_user }}/.dotfiles
  register: dotfiles_dir

- name: Clone a repo with separate git directory
  ansible.builtin.git:
    repo: https://github.com/Gedulis12/dotfiles
    dest: /home/{{ ansible_user }}/dotfiles-tmp
    separate_git_dir: /home/{{ ansible_user }}/.dotfiles
    update: no
  when: not dotfiles_dir.stat.exists
  notify: 
    - Copy configs from temp dir.
    - Remove temp dir.
    - Remove .git from home.
    - Apply changes to git config.

- name: Pull changes if repository exists
  ansible.builtin.git:
    repo: https://github.com/Gedulis12/dotfiles
    dest: /home/{{ ansible_user }}/dotfiles-tmp
    update: yes
  notify: 
    - Copy configs from temp dir.
    - Remove temp dir.
    - Remove .git from home.
