---
- name: Make sure that required packages are installed
  become: true
  package:
    name: "{{ item }}"
    state: present
  loop:
    - "{{ docker_packages }}"

- name: Make sure a docker group is present
  become: true
  group:
    name: docker
    state: present

- name: Add user to docker group
  become: true
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Make sure a docker service unit is running
  become: true
  ansible.builtin.systemd:
    state: started
    name: docker

- name: Create a docker directory if it does not exist
  ansible.builtin.file:
    path: "{{ docker_home_dir }}"
    state: directory
    mode: '0755'
    group: "{{ ansible_user }}"
    owner: "{{ ansible_user }}"
