---
# docker config
docker_home_dir: '/home/{{ ansible_user }}/docker' # home dir for docker configs
timezone: "Europe/Vilnius"

# rpi-monitor config
rpi_monitor:
  ip: 192.168.0.210
  port: 8888
  fqdn: rpi-monitor.lan

# wireguard config
wg_port: 51820
wg_peer_count: 2
wg_internal_subnet: 10.13.13.0
wg_logs_enabled: true

# thelounge config (irc web client)
thelounge:
  ip: 192.168.0.210
  fqdn: irc.lan
  port: 9999

# gitea config
gitea:
  ip: 192.168.0.210
  fqdn: gitea.lan
  port: 3000
  ssh_port: 222
  network: gitea
  db:
    user: gitea
    password: gitea
    database: gitea
    root_password: gitea

# pihole config
pihole:
  ip: 192.168.0.210
  port: 83
  https_port: 9443
  fqdn: pihole.lan
  webpass: "password"

# jellyfin config
jellyfin:
  ip: 192.168.0.135
  port: 8096
  fqdn: jellyfin.lan
  volumes:
    tv_shows_dir: /data/media/tv
    movies_dir: /data/media/tv
    music_dir: /data/media/music
    stand_up_comedy_dir: /data/media/stand-up-comedy
    other_media_dir: /data/media/other
    podcasts_dir: /data/media/podcasts

# nginx config
nginx:
  http_port: 80
  https_port: 443
