---
# docker config
docker_home_dir: '/home/{{ ansible_user }}/docker' # home dir for docker configs
timezone: "Europe/Vilnius"

# rpi-monitor config
rpi_monitor_port: 8888

# wireguard config
wg_port: 51820
wg_peer_count: 2
wg_internal_subnet: 10.13.13.0
wg_logs_enabled: true

# thelounge config (irc web client)
thelounge_port: 9999

# gitea config
gitea:
  web_ui_port: 3000
  ssh_port: 222
  db_user: gitea
  db_password: gitea
  db_database: gitea
  db_root_password: gitea
  network: gitea

# pihole config
pihole_web_ui_port: 83
pihole_https_port: 9443
pihole_server_ip: 192.168.0.210
pihole_webpass: "password"

# jellyfin config
jellyfin:
  port: 8096
  volumes:
    tv_shows_dir: /data/media/tv
    movies_dir: /data/media/tv
    music_dir: /data/media/music
    stand_up_comedy_dir: /data/media/stand-up-comedy
    other_media_dir: /data/media/other
    podcasts_dir: /data/media/podcasts
