- hosts: vms
  become: true

  pre_tasks:
    - name: Load configuration.
      ansible.builtin.include_vars: "{{ item }}"
      loop:
        - config.default.yml
        - config.yml

  roles:
    - git
    - pihole
    - irc
    - wireguard
    - dotfiles
